//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArkadeTestDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArkadeTestDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Core.Resources.ArkadeTestDisplayNames", typeof(ArkadeTestDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records.
        /// </summary>
        public static string A_01 {
            get {
                return ResourceManager.GetString("A_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of characters.
        /// </summary>
        public static string A_02 {
            get {
                return ResourceManager.GetString("A_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_03 {
            get {
                return ResourceManager.GetString("A_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_04 {
            get {
                return ResourceManager.GetString("A_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_05 {
            get {
                return ResourceManager.GetString("A_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_07 {
            get {
                return ResourceManager.GetString("A_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_08 {
            get {
                return ResourceManager.GetString("A_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_09 {
            get {
                return ResourceManager.GetString("A_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of instances of values for fields.
        /// </summary>
        public static string A_10 {
            get {
                return ResourceManager.GetString("A_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_11 {
            get {
                return ResourceManager.GetString("A_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_12 {
            get {
                return ResourceManager.GetString("A_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_13 {
            get {
                return ResourceManager.GetString("A_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_14 {
            get {
                return ResourceManager.GetString("A_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_15 {
            get {
                return ResourceManager.GetString("A_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_16 {
            get {
                return ResourceManager.GetString("A_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_17 {
            get {
                return ResourceManager.GetString("A_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_18 {
            get {
                return ResourceManager.GetString("A_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_19 {
            get {
                return ResourceManager.GetString("A_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_20 {
            get {
                return ResourceManager.GetString("A_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_21 {
            get {
                return ResourceManager.GetString("A_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_22 {
            get {
                return ResourceManager.GetString("A_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_32 {
            get {
                return ResourceManager.GetString("A_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_33 {
            get {
                return ResourceManager.GetString("A_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_34 {
            get {
                return ResourceManager.GetString("A_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_35 {
            get {
                return ResourceManager.GetString("A_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A_36 {
            get {
                return ResourceManager.GetString("A_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AH_01 {
            get {
                return ResourceManager.GetString("AH_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AH_02 {
            get {
                return ResourceManager.GetString("AH_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AH_03 {
            get {
                return ResourceManager.GetString("AH_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AI_01 {
            get {
                return ResourceManager.GetString("AI_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string DisplayNameFormat {
            get {
                return ResourceManager.GetString("DisplayNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_01 {
            get {
                return ResourceManager.GetString("N5_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_02 {
            get {
                return ResourceManager.GetString("N5_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_03 {
            get {
                return ResourceManager.GetString("N5_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of archives.
        /// </summary>
        public static string N5_04 {
            get {
                return ResourceManager.GetString("N5_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of archive parts.
        /// </summary>
        public static string N5_05 {
            get {
                return ResourceManager.GetString("N5_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_06 {
            get {
                return ResourceManager.GetString("N5_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of classification systems.
        /// </summary>
        public static string N5_07 {
            get {
                return ResourceManager.GetString("N5_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Number of bins.
        /// </summary>
        public static string N5_08 {
            get {
                return ResourceManager.GetString("N5_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of classes in the primary classification system without subclasses, folders or registrations.
        /// </summary>
        public static string N5_09 {
            get {
                return ResourceManager.GetString("N5_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of folders to apply the view to: &lt;0d&gt;.
        /// </summary>
        public static string N5_10 {
            get {
                return ResourceManager.GetString("N5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of folders for each year.
        /// </summary>
        public static string N5_11 {
            get {
                return ResourceManager.GetString("N5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_12 {
            get {
                return ResourceManager.GetString("N5_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of folders for each class.
        /// </summary>
        public static string N5_13 {
            get {
                return ResourceManager.GetString("N5_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of folders without registrations or subfolders.
        /// </summary>
        public static string N5_14 {
            get {
                return ResourceManager.GetString("N5_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of different case folder statuses.
        /// </summary>
        public static string N5_15 {
            get {
                return ResourceManager.GetString("N5_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of recording made for framework : %1 and industry : %2 is %3.
        /// </summary>
        public static string N5_16 {
            get {
                return ResourceManager.GetString("N5_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of different journal entry types.
        /// </summary>
        public static string N5_17 {
            get {
                return ResourceManager.GetString("N5_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_18 {
            get {
                return ResourceManager.GetString("N5_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_19 {
            get {
                return ResourceManager.GetString("N5_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_20 {
            get {
                return ResourceManager.GetString("N5_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_21 {
            get {
                return ResourceManager.GetString("N5_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of different journal statuses.
        /// </summary>
        public static string N5_22 {
            get {
                return ResourceManager.GetString("N5_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document descriptions.
        /// </summary>
        public static string N5_23 {
            get {
                return ResourceManager.GetString("N5_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document descriptions without document object.
        /// </summary>
        public static string N5_24 {
            get {
                return ResourceManager.GetString("N5_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of different document statuses.
        /// </summary>
        public static string N5_25 {
            get {
                return ResourceManager.GetString("N5_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document objects.
        /// </summary>
        public static string N5_26 {
            get {
                return ResourceManager.GetString("N5_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_27 {
            get {
                return ResourceManager.GetString("N5_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_28 {
            get {
                return ResourceManager.GetString("N5_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of different document formats.
        /// </summary>
        public static string N5_29 {
            get {
                return ResourceManager.GetString("N5_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_30 {
            get {
                return ResourceManager.GetString("N5_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_32 {
            get {
                return ResourceManager.GetString("N5_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_33 {
            get {
                return ResourceManager.GetString("N5_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_34 {
            get {
                return ResourceManager.GetString("N5_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_35 {
            get {
                return ResourceManager.GetString("N5_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parties.
        /// </summary>
        public static string N5_35v5_5 {
            get {
                return ResourceManager.GetString("N5_35v5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of notes.
        /// </summary>
        public static string N5_36 {
            get {
                return ResourceManager.GetString("N5_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cross-references.
        /// </summary>
        public static string N5_37 {
            get {
                return ResourceManager.GetString("N5_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of precedents.
        /// </summary>
        public static string N5_38 {
            get {
                return ResourceManager.GetString("N5_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of correspondence parties.
        /// </summary>
        public static string N5_39 {
            get {
                return ResourceManager.GetString("N5_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of depreciation.
        /// </summary>
        public static string N5_40 {
            get {
                return ResourceManager.GetString("N5_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document flows.
        /// </summary>
        public static string N5_41 {
            get {
                return ResourceManager.GetString("N5_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_42 {
            get {
                return ResourceManager.GetString("N5_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_43 {
            get {
                return ResourceManager.GetString("N5_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_44 {
            get {
                return ResourceManager.GetString("N5_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_45 {
            get {
                return ResourceManager.GetString("N5_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of converted documents.
        /// </summary>
        public static string N5_46 {
            get {
                return ResourceManager.GetString("N5_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_47 {
            get {
                return ResourceManager.GetString("N5_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_48 {
            get {
                return ResourceManager.GetString("N5_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_51 {
            get {
                return ResourceManager.GetString("N5_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of journal entries.
        /// </summary>
        public static string N5_59 {
            get {
                return ResourceManager.GetString("N5_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet period start and end dates.
        /// </summary>
        public static string N5_60 {
            get {
                return ResourceManager.GetString("N5_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of logged changes.
        /// </summary>
        public static string N5_61 {
            get {
                return ResourceManager.GetString("N5_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_62 {
            get {
                return ResourceManager.GetString("N5_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string N5_63 {
            get {
                return ResourceManager.GetString("N5_63", resourceCulture);
            }
        }
    }
}
