//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Core.Resources.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd. MMMM yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade 5 versjon: {0}.
        /// </summary>
        public static string FooterArkadeVersion {
            get {
                return ResourceManager.GetString("FooterArkadeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testrapport.
        /// </summary>
        public static string HeadingTestReport {
            get {
                return ResourceManager.GetString("HeadingTestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultater.
        /// </summary>
        public static string HeadingTestResults {
            get {
                return ResourceManager.GetString("HeadingTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyser og kontroller.
        /// </summary>
        public static string HeadingTests {
            get {
                return ResourceManager.GetString("HeadingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testsammendrag.
        /// </summary>
        public static string HeadingTestSummary {
            get {
                return ResourceManager.GetString("HeadingTestSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkivskaper.
        /// </summary>
        public static string LabelArchiveCreators {
            get {
                return ResourceManager.GetString("LabelArchiveCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkivperiode.
        /// </summary>
        public static string LabelArchivePeriod {
            get {
                return ResourceManager.GetString("LabelArchivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkivtype.
        /// </summary>
        public static string LabelArchiveType {
            get {
                return ResourceManager.GetString("LabelArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidspunkt for testing.
        /// </summary>
        public static string LabelDateOfTesting {
            get {
                return ResourceManager.GetString("LabelDateOfTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall avvik funnet.
        /// </summary>
        public static string LabelNumberOfErrors {
            get {
                return ResourceManager.GetString("LabelNumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall filer som er prosessert.
        /// </summary>
        public static string LabelNumberOfFilesProcessed {
            get {
                return ResourceManager.GetString("LabelNumberOfFilesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall poster som er prosessert.
        /// </summary>
        public static string LabelNumberOfRecordsProcessed {
            get {
                return ResourceManager.GetString("LabelNumberOfRecordsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall tester utført.
        /// </summary>
        public static string LabelNumberOfTestsExecuted {
            get {
                return ResourceManager.GetString("LabelNumberOfTestsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall tester som er kjørt.
        /// </summary>
        public static string LabelNumberOfTestsRun {
            get {
                return ResourceManager.GetString("LabelNumberOfTestsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemnavn.
        /// </summary>
        public static string LabelSystemName {
            get {
                return ResourceManager.GetString("LabelSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemtype.
        /// </summary>
        public static string LabelSystemType {
            get {
                return ResourceManager.GetString("LabelSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uuid.
        /// </summary>
        public static string LabelUuid {
            get {
                return ResourceManager.GetString("LabelUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasjon.
        /// </summary>
        public static string TestLocation {
            get {
                return ResourceManager.GetString("TestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        public static string TestMessage {
            get {
                return ResourceManager.GetString("TestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} flere resultater av samme type..
        /// </summary>
        public static string TestMoreResultsOfSameKind {
            get {
                return ResourceManager.GetString("TestMoreResultsOfSameKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen avvik funnet..
        /// </summary>
        public static string TestNoErrorsFound {
            get {
                return ResourceManager.GetString("TestNoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innholdsanalyse.
        /// </summary>
        public static string TestTypeContentAnalysisDisplayName {
            get {
                return ResourceManager.GetString("TestTypeContentAnalysisDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innholdskontroll.
        /// </summary>
        public static string TestTypeContentControlDisplayName {
            get {
                return ResourceManager.GetString("TestTypeContentControlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strukturanalyse.
        /// </summary>
        public static string TestTypeStructureAnalysisDisplayName {
            get {
                return ResourceManager.GetString("TestTypeStructureAnalysisDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strukturkontroll.
        /// </summary>
        public static string TestTypeStructureControlDisplayName {
            get {
                return ResourceManager.GetString("TestTypeStructureControlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke alle tester er utført.
        /// </summary>
        public static string WarningNotAllTestsExecuted {
            get {
                return ResourceManager.GetString("WarningNotAllTestsExecuted", resourceCulture);
            }
        }
    }
}
